version: "3"
services:
  nginx:
    build: ./srcs/nginx
    ports:
      - "443:443"
    restart: always
    networks:
      inception:
  wordpress:
    build: ./srcs/wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      DB_HOST: mariadb
      DB_USER: {$DB_USER}
      DB_PASS: {$DB_PASS}
      DB_NAME: {$DB_NAME}
    # volumes:
    #   wp_data:/var/www/html
    networks:
      inception:
  mariadb:
    build: ./srcs/mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      DB_NAME: {$DB_NAME}
      DB_PASS: {$DB_PASS}
    # volumes:
    #   - ./mysql:/var/lib/mysql
    networks:
      inception:
networks:
  inception:

